# Generated by Django 3.2.25 on 2025-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0101_historicalproblem_evaluation_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
