# Generated by Django 3.2.25 on 2025-08-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0102_alter_userevaluation_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationProblemTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('evaluation_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.evaluationproblem')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.testcase')),
            ],
            options={
                'unique_together': {('evaluation_problem', 'test_case')},
            },
        ),
        migrations.AddField(
            model_name='evaluationproblem',
            name='selected_test_cases',
            field=models.ManyToManyField(related_name='evaluation_problems', through='questions.EvaluationProblemTestCase', to='questions.TestCase'),
        ),
    ]
