# Generated by Django 3.2.25 on 2025-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0104_evaluation_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationproblemtestcase',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userevaluation',
            name='needs_manual_grading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userevaluationproblem',
            name='autograder_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevaluationproblem',
            name='show_test_cases_in_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userevaluationproblem',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
