# Generated by Django 3.2.25 on 2025-11-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0105_auto_20250908_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationproblem',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.language'),
        ),
    ]
